export { default as HeroSection } from './HeroSection'
export { default as ServicesSection } from './ServicesSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as PricingSection } from './PricingSection'
export { default as GallerySection } from './GallerySection'
export { default as FaqSection } from './FaqSection'
export { default as BookingCtaSection } from './BookingCtaSection'
