export { default as HeroSection } from './HeroSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as ServicesSection } from './ServicesSection'
export { default as GallerySection } from './GallerySection'
export { default as PricingSection } from './PricingSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as ProjectsSection } from './ProjectsSection'
export { default as ContactSection } from './ContactSection'
